name: Build documentation
on: workflow_dispatch

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install deps
        run: >
          sudo apt-get update &&
          sudo apt-get install
          clang-15
          g++-12
          libc++-15-dev
          libc++abi-15-dev
          libomp-15-dev
      
      - name: Get versions
        run: python --version && flex --version && bison --version

      - name: Check llvm
        run: ll /usr/lib/llvm-15/ && ll /usr/lib/llvm-15/lib/cmake/clang/

      - name: Build doxygen
        run: git clone https://github.com/doxygen/doxygen.git &&
          cd doxygen && 
          mkdir build && 
          cd build &&
          cmake .. -Duse_libclang=ON -DCMAKE_CXX_COMPILER=clang++-15 -DCMAKE_C_COMPILER=clang-15 &&
          make &&
          make install &&
          doxygen --version

