name: Build documentation
on: workflow_dispatch

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install deps
        run: >
          sudo apt-get update &&
          sudo apt-get install
          llvm-15
          llvm-15-dev
          llvm-15-tools
          llvm-15-runtime
          clang-15
          clang-format-15
          libclang-common-15-dev
          libclang-15-dev
          libclang-cpp15
          libclang1-15
          libllvm15
          g++-12
          libc++-15-dev
          libc++abi-15-dev
          libomp-15-dev

      - name: Build doxygen
        run: |
          git clone https://github.com/doxygen/doxygen.git
          cd doxygen
          mkdir build
          cd build
          cmake .. -Duse_libclang=ON -DLLVM_ROOT=/usr/lib/llvm-15/lib/cmake/llvm -DCLANG_ROOT=/usr/lib/llvm-15/lib/cmake/clang -DCMAKE_CXX_COMPILER=clang++-15 -DCMAKE_C_COMPILER=clang-15
          make
          make install
          doxygen --version

