name: Hello Workflow
on: workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello ${{ github.actor }}!"
